sudo: false

language: php

php:
    - 7.1
    - 7.2
    - 7.3

# test only master (+ Pull requests)
branches:
    only:
        - master

before_script:
    - phpenv config-rm xdebug.ini
    - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - travis_retry composer selfupdate
    - composer config -g github-oauth.github.com "d0285ed5c8644f30547572ead2ed897431c1fc09"
    - travis_retry composer install --prefer-dist --no-interaction

script: php vendor/bin/phpunit

notifications:
    email: false
